-- VisionQuest Database Schema
-- Users und Quests für AR-Gaming-App

-- Users Tabelle
CREATE TABLE IF NOT EXISTS USERS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USERNAME VARCHAR(50) UNIQUE NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    LEVEL INTEGER DEFAULT 1,
    XP INTEGER DEFAULT 0,
    STREAK_DAYS INTEGER DEFAULT 0,
    LAST_QUEST_DATE DATE,
    THEME VARCHAR(20) DEFAULT 'default',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Quests Tabelle
CREATE TABLE IF NOT EXISTS QUESTS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID INTEGER NOT NULL,
    TITLE VARCHAR(100) NOT NULL,
    DESCRIPTION TEXT,
    CATEGORY VARCHAR(50) NOT NULL,
    DIFFICULTY VARCHAR(20) DEFAULT 'medium',
    XP_REWARD INTEGER DEFAULT 100,
    STATUS VARCHAR(20) DEFAULT 'active',
    IMAGE_PATH VARCHAR(255),
    DETECTED_OBJECT VARCHAR(100),
    COMPLETED_AT TIMESTAMP,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);

-- User Stats Tabelle (für detaillierte Statistiken)
CREATE TABLE IF NOT EXISTS USER_STATS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID INTEGER UNIQUE NOT NULL,
    TOTAL_QUESTS_COMPLETED INTEGER DEFAULT 0,
    TOTAL_SCANS INTEGER DEFAULT 0,
    LONGEST_STREAK INTEGER DEFAULT 0,
    FAVORITE_CATEGORY VARCHAR(50),
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);

-- Achievements Tabelle
CREATE TABLE IF NOT EXISTS ACHIEVEMENTS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID INTEGER NOT NULL,
    ACHIEVEMENT_NAME VARCHAR(100) NOT NULL,
    ACHIEVEMENT_DESCRIPTION TEXT,
    UNLOCKED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);

-- Indexes für Performance
CREATE INDEX IF NOT EXISTS IDX_USERS_EMAIL ON USERS(EMAIL);

CREATE INDEX IF NOT EXISTS IDX_USERS_USERNAME ON USERS(USERNAME);

CREATE INDEX IF NOT EXISTS IDX_QUESTS_USER_ID ON QUESTS(USER_ID);

CREATE INDEX IF NOT EXISTS IDX_QUESTS_STATUS ON QUESTS(STATUS);

CREATE INDEX IF NOT EXISTS IDX_USER_STATS_USER_ID ON USER_STATS(USER_ID);